[project]
name = "dpz-index"
version = "0.1.0"
description = "QGIS plugin to add DPZ index"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "qgis-plugin-ci>=2.8.9",
]

[tool.qgis-plugin-ci]
plugin_path = "dpz_index"
