on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --dev

      - name: Lint
        run: |
          uvx ruff format --check dpz_index

      - name: Build plugin
        run: |
          VERSION=$(grep version pyproject.toml | cut -d" " -f3 | tr -d '"')
          uvx qgis-plugin-ci package ${VERSION}

      - uses: actions/upload-artifact@v4
        if: github.ref_type == 'tag'
        with:
          path: ./*.zip
          if-no-files-found: error

  # in order to minimize the scope of write permission, use a separate step
  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.ref_type == 'tag'
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      # To use gh command, it expects repository
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4

      - name: Release
        run: |
          VERSION=$(grep version pyproject.toml | cut -d" " -f3 | tr -d '"')

          # check version
          if [ "${{ github.ref_name }}" != v"${VERSION}" ]; then
            echo "Version doesn't match! (tag: ${{ github.ref_name }}, pyproject.toml: ${VERSION})"
            exit 1
          fi

          gh release create ${{ github.ref_name }} ./artifact/*.zip
