on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --dev

      - name: Lint
        run: |
          uvx ruff format --check dpz_index

      - name: Build plugin
        run: |
          VERSION=$(grep version pyproject.toml | cut -d" " -f3 | tr -d '"')
          uvx qgis-plugin-ci package ${VERSION}

      - uses: actions/upload-artifact@v4
        # if: github.ref_type == 'tag'
        with:
          path: ./*.zip
          if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # if: github.ref_type == 'tag'
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/download-artifact@v4

      - name: Release
        run: |
          # test
          VERSION=$(grep version pyproject.toml | cut -d" " -f3 | tr -d '"')
          gh release create ${VERSION} ./*.zip
