on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --dev

      - name: Lint
        run: |
          uvx ruff format --check dpz_index

      - name: Test building plugin
        run: |
          VERSION=$(grep version pyproject.toml | cut -d" " -f3 | tr -d '"')
          uvx qgis-plugin-ci package $(VERSION)
